services:
  mongo:
    image: mongo:latest
    ports:
      - "3002:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_CONNECT_TIMEOUT: 30000
    networks:
      - dongy
    restart: always

volumes:
  mongo-data: {}
networks:
  dongy:
    driver: bridge
