version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "3002:27017"
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_CONNECT_TIMEOUT: ${MONGO_INITDB_CONNECT_TIMEOUT}
    networks:
      - dongy
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - dongy
    restart: always

volumes:
  mongo_data: 
  redis_data:

networks:
  dongy:
    driver: bridge
