// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/utils/token/token.go
//
// Generated by this command:
//
//	mockgen -source=pkg/utils/token/token.go -destination=pkg/mock/token/token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock
